services:
  # Auth Service
  auth-service:
    build: ./services/auth
    env_file:
      - ./services/auth/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend

  # PostgreSQL (for auth-service)
  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - backend
  expense-service:
    build: ./services/expense
    env_file:
      - ./services/expense/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
